# Configuration for the academic website

site_name: "Mengfei Zhao"
base_url: "/"
theme: "academic"
plugins:
  - "about"
  - "projects"
pages:
  - path: index
    title: "Home"
    content: |
      ## Introduction
      I am a third-year student at Southern University of Science and Technology (SUSTech), majoring in Intelligent Science in the Computer Science and Engineering Department. I am currently participating in the UCSD 2025 Spring Extension Program and working on combining pruning and optimization in Reinforcement Learning. After completing my undergraduate studies, I plan to pursue a PhD in RL.

      ## Research Interests
      Reinforcement Learning, Pruning, World Model, Zero-Order Optimization, Evolutionary Computation, Neural Architecture Search.
      
      ## Education
      - **Southern University of Science and Technology** (2022 – 2024)
        - GPA: 3.91/4.00, Top 3% (Overall)
        - Rank 1/21 in Major (2023-2024)

      ## Experience
      ### Evolving Machine Intelligence (EMI) Group (July 2023 – Dec 2023)
      - Simplified NEAT algorithm design, optimized hyperparameters, and implemented tensorization and parallel computing techniques.

      ### EMI NeuroEvolution Subgroup Leader (Dec 2023 – Present)
      - Leading a team of 5 members, focusing on pruning and optimization in RL problems.
      
  - path: projects
    title: "Projects"
    content: |
      ## TensorNEAT
      [GitHub Link](https://github.com/EMI-Group/tensorneat)
      - Implemented the NEAT algorithm using JAX for tensorized representation and parallel computation. Achieved a 10-100x speedup compared to Python-NEAT.

      ## GECCO Interpretable Control Competition
      - Achieved second place in GECCO 2024 Interpretable Control Competition by combining neural evolution and pruning techniques.
      
      ## INCEPT Algorithm
      - Independently designed the INCEPT algorithm, achieving up to 97% pruning rate on humanoid tasks. Preparing submission to *Nature Machine Intelligence*.
  
  - path: about
    title: "About Me"
    content: |
      ## About Me
      I'm passionate about Reinforcement Learning and its applications in real-world scenarios. I enjoy tackling complex problems and pushing the boundaries of machine learning. Outside of my academic work, I like playing video games, reading science fiction, and learning new technologies.

      ## Contact
      - Email: [zhaomengfei248@gmail.com](mailto:zhaomengfei248@gmail.com)
      - Phone: +86 152-5198-5736
